### ISSUE TITLE
Up Vote

### ISSUE THREAD

**Issue by fredboys** [fredboys/my-backend#10]
As a **developer** I need to create a  **Up Vote app** so that **I can provide a trending products section**

# Acceptance Criteria

* Votes can be retrieved by id
* votes list can be seen on each product

# Tasks

- [x] create votes app
- [x] create model, serializer and view
- [x] add to setting.py
