### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by fredboys** [fredboys/my-backend#12]
As a **developer** I need to create and access the contact form from the admin so that **I can review any feedback** so that **I can improve the site**

# Acceptance Criteria

* comments are sent back to the api for the site owner to see

# Tasks

- [x] create contact app
- [x] create model, serializer and view
- [x] add to setting.py
