### ISSUE TITLE
Favourite

### ISSUE THREAD

**Issue by fredboys** [fredboys/my-backend#7]
As a **developer** I need create a **favourite app** so that **users can save products for later**

# Acceptance Criteria

* A product can be retrieved by id
* Can list all favourites made by an owner

# Tasks

- [x] Create favourite app
- [x] create model, view and serializer
- [x] add to setting.py
