### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by fredboys** [fredboys/my-backend#8]
As a **developer** I need to **create a comment app** so that **users can share thoughts and build a community**

# Acceptance Criteria

* Comments can be retrieved by id
* Can view the list of comments made on a product

# Tasks

- [x] create comments app
- [x] create model, serializer and view
- [x] add to setting.py
